name: PVE API CodeGen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  deno-version: v1.36.x

jobs:
  check-and-compile:
    name: Check and Compile pve-api-codegen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.deno-version }}

      - name: Deno fmt
        run: make fmt-check
      - name: Deno lint
        run: make lint
      - name: Deno check
        run: make type-check
      - name: Deno Compile
        run: make compile

      - name: Tar binary
        if: github.ref == 'refs/heads/main'
        run: tar -zcvf pve-api-codegen.tar.gz pve-api-codegen
      - name: Upload binary
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: pve-api-codegen.tar.gz
          path: pve-api-codegen.tar.gz
          if-no-files-found: error
          retention-days: 14
